#                         The MIT License
#
# Copyright (c) 2013 Marcelo Guimarães <ataxexe@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

module Yummi

  class Generator

    class ShellScript

      def generate
        content = <<END
#!/bin/sh

# .:: Generated by Yummi ::.

usage() {
  echo "Usage: $0 COLOR TEXT [FORMAT]"
  echo "  Because this program is intented to be used inside scripts, the colorized text will NOT come with a line break"

  exit 1
}
END
        Yummi::Color::COLORS.each do |key, pattern|
          function = <<FUNCTION
function color_#{key} {
  echo \"#{"$1".colorize(key)}\"
}
FUNCTION
          content << function
        end

        end_script = <<END

[ "$#" = "0" ] && usage

format="%s"

[ ! -z "$3" ] && format="$3"

printf "$format" $(\"color_$@\")
  
END
        content << end_script

        content
      end

      def install
        puts ".: Yummi shell script installation :.".colorize(:bold_yellow)
        name = get "Program name", "color"
        location = File.expand_path(get("Install location", "~/bin"))
        file = File.join(location, name)
        File.open(file, "w") { |f| f.write generate }
        File.chmod(0755, file)
        puts "Program installed!"
      end

      private

      def get message, default
        puts(message.colorize(:blue) << ": " << " [#{default}]".colorize(:yellow))
        input = gets.chomp
        return default if input.empty?
        input
      end
    end

  end

end